name: CI

on: [push, pull_request]

jobs:
  svecl:
    name: svecl CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: 'go build ./cmd/...'
    - name: Test
      run: 'go test -v ./...'
